### PR TITLE
Bugfix/netcdf cxx4 macos

### PR DESCRIPTION
**Pull request by skosukhin**
@climbfuji could you, please, check whether this works for you? If it does, please, merge it into your branch (with `--ff-only`) so that https://github.com/spack/spack/pull/29246 got updated automatically and we merged it there. If you don't like this approach for whatever reason, I can create a separate PR upstream.

### CODE REVIEW

**Comment by climbfuji** [comment]
@skosukhin Thanks, I am testing this today, will let you know how it goes.

**Comment by climbfuji** [comment]
@skosukhin Unfortunately using your version gives a ton of errors on macOS:
```
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/string:520:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/__functional_base:15:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/__functional/invoke.h:14:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/__functional/weak_result_type.h:16:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/type_traits:420:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/cstddef:37:
../version:1:1: error: expected external declaration
-n 4.3.1
^
../version:1:2: error: unknown type name 'n'
-n 4.3.1
 ^
../version:1:4: error: expected unqualified-id
-n 4.3.1
   ^
In file included from ncAtt.cpp:1:
In file included from ./ncAtt.h:1:
In file included from ./ncType.h:1:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/string:520:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/__functional_base:15:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/__functional/invoke.h:14:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/__functional/weak_result_type.h:16:
In file included from /usr/local/opt/llvm/bin/../include/c++/v1/type_traits:421:
../version:1:1: error: expected external declaration
-n 4.3.1
^
../version:1:2: error: unknown type name 'n'
...
```
These look a lot like what the patch in both our versions is supposed to fix, and it does say in the logs that the patch is applied. I checked `configure.ac` in the spack-src dir, and it has
```
echo -n AC_PACKAGE_VERSION>VERSION.txt
```
however in the same directory the file is called `VERSION`. Is autotools not called correctly in this new version? Attaching the full logs here.

[spack-install-netcdfcxx4.tar.gz](https://github.com/climbfuji/spack/files/8186656/spack-install-netcdfcxx4.tar.gz)

**Comment by skosukhin** [comment]
@climbfuji I'm sorry. I forgot that the patch implies running `autoreconf`, which I'd like to avoid. Does it work now?

**Comment by climbfuji** [comment]
Yes, @skosukhin this works on macOS now. I am going to test it on one of our finicky HPC systems later today as well, because there are quite a few changes in your PR.

**Pull request merged**
